theme: jekyll-theme-minimal
title: Calendarific SDK .NET
description: A template repository for .NET API clients projects.
logo: https://raw.githubusercontent.com/guibranco/calendarific-sdk-dotnet/main/logo.png
show_downloads: true
