name: Label based on PR size

on:
  pull_request:
  workflow_dispatch:

jobs:
  size-label:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:

      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.2"
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
     
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test /p:CollectCoverage=true
        working-directory: ./Tests/Calendarific.UnitTests

